name: Build APK REAL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar projeto pronto
        run: |
          git clone https://github.com/android/architecture-samples.git app

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APK
        run: |
          cd app
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-real
          path: app/**/build/outputs/apk/debug/*.apk
